### ISSUE TITLE
Tareas -> Pedidos de trabajo: No aparece el campo "Motivo de rechazo" que permite rechazar una tarea

### ISSUE THREAD

**Issue by Nahuel1705** [Trazalog/yudi-tools-almproc#1]
Descripción: Si se quiere rechazar una revisión inicial aparece un mensaje emergente diciendo "Completar Motivo de Rechazo" pero en ningún lado aparece este campo para ingresar el motivo. La tarea queda pendiente y solo se puede avanzar en el proceso.

Pasos para la reproducción:

1. Tomar una tarea disponible
2. Seleccionar el radial "rechazar" cuando pregunte "¿Se Aprueba Trabajo?"

Comportamiento esperado:
Cuando se selecciona el radial "rechazar" debería aparecer un formulario dinámico que permita cargar el motivo del rechazo, posteriormente se imprime el comprobante de rechazo.

![chrome-capture](https://user-images.githubusercontent.com/56811317/121963502-92d58580-cd40-11eb-8682-63fd34e2c031.gif)

**Comment by aalfaro-trazalog** [comment]
@lbgarcia este ya está solucionado!
