### ISSUE TITLE
Almacenes--> problemas para ver la trazabilidad en pedidos de materiales

### ISSUE THREAD

**Issue by aalfaro-trazalog** [Trazalog/yudi-tools-almproc#102]
v 2.0.15.3

Descripción:
Cuando se lanza un pedido de materiales, en la trazabilidad no se muestra en que paso está, pero en bonita si.

![image](https://user-images.githubusercontent.com/87376576/175545548-5d107c7a-093a-459c-a8df-eb227388a703.png)

![image](https://user-images.githubusercontent.com/87376576/175545017-5a1dc3dc-cb30-46bc-9450-a816c623dc82.png)

**Comment by floto-trazalog** [comment]
Solucionado en v2.3.11
