### ISSUE TITLE
Tareas--> Pedido de Materiales: indicar campo obligatorio

### ISSUE THREAD

**Issue by aalfaro-trazalog** [Trazalog/yudi-tools-almproc#105]
v 2.0.16 (Ambiente test)

Descripción:
Cuando se rechaza el pedido de materiales, si no se ingresa el motivo, da error. 
Agregar una descripción del campo, que muestre la obligatoriedad del mismo y mejorar el cartel de la alerta para cuando el usuario olvide completarlo.

![image](https://user-images.githubusercontent.com/87376576/176902488-43482197-59b3-4f89-add2-aaf8f90c5708.png)

**Comment by floto-trazalog** [comment]
Solucionado
