### ISSUE TITLE
Soporte--> Embandado: Agregar al menú, crear pedido de almacén

### ISSUE THREAD

**Issue by aalfaro-trazalog** [Trazalog/yudi-tools-almproc#107]
v 2.0.15.5

Descripción:
Al usuario yudica.embandado@gmail.com agregarle el permiso de poder generar pedidos de materiales en almacén.

https://user-images.githubusercontent.com/87376576/178739078-eeb8f9d6-9787-4d01-84ee-495f4d303c67.mp4

**Comment by floto-trazalog** [comment]
Solucionado
