### ISSUE TITLE
Soporte--> Pedidos de trabajo: no ordena bien por fecha

### ISSUE THREAD

**Issue by aalfaro-trazalog** [Trazalog/yudi-tools-almproc#116]
Ambiente cliente PRD v 2.1.4.5

Descripción:
Al ingresar a la bandeja de pedidos, deberían aparecer en orden por última fecha, es decir por el pedido de trabajo mas reciente en el tope.

![image](https://user-images.githubusercontent.com/87376576/189425091-0ec5e93a-bab9-4fef-b011-f0a71525a72d.png)

**Comment by floto-trazalog** [comment]
Solucionado
