### ISSUE TITLE
Soporte--> Almacenes: En pedido de materiales que se muestre la descripción del artículo

### ISSUE THREAD

**Issue by aalfaro-trazalog** [Trazalog/yudi-tools-almproc#120]
v 2.1.4.9

Descripción:
En pedido de materiales que se muestre la descripción del artículo

![image](https://user-images.githubusercontent.com/87376576/191114480-98ae251d-b4a5-47a8-86a0-608e59fce70a.png)

Pasos para reproducir:
1. En menú seleccionar Almacenes
2. Click en Salida de depósito

**Comment by floto-trazalog** [comment]
Solucionado en v2.1.7.6
