### ISSUE TITLE
Tareas-->Pedido de trabajo: Al eliminar un pedido se pierde el estilo de los estados

### ISSUE THREAD

**Issue by aalfaro-trazalog** [Trazalog/yudi-tools-almproc#126]
v2.1.7 Ambiente PROD

Descripción:
Cuando se elimina un pedido de trabajo, luego se pierde el estilo de los estados. Al recargar página se soluciona.

![image](https://user-images.githubusercontent.com/87376576/194149976-6c82efc8-9efa-4639-b5e1-a8a4a25ac797.png)

**Comment by floto-trazalog** [comment]
Solucionado en v2.2
