### ISSUE TITLE
Soporte--> Almacenes:  No funciona el filtro por depósito.

### ISSUE THREAD

**Issue by aalfaro-trazalog** [Trazalog/yudi-tools-almproc#128]
v 2.1.7 - Ambiente PROD

Descripción:
 No está funcionando el filtro de almacenes para separar los artículos por depósito.

https://user-images.githubusercontent.com/87376576/195357591-57b3ba83-3c1c-462f-aa95-88c518a50871.mp4

**Comment by floto-trazalog** [comment]
Se desestima el reporte porque el usuario, previamente, debe agregar el encargado al depósito:

En Configuración-->ABM Establecimientos-->Botón de acción "Depósito"-->Seleccionar el/los encargado/s del depósito

![image](https://user-images.githubusercontent.com/88331456/196773414-60202033-4ffd-4128-8c66-8b98ea5ffc0f.png)
