### ISSUE TITLE
SOPORTE-->Tareas-->Pedidos trabajo: la ventana de pedidos de trabajo no recupera el form completo 

### ISSUE THREAD

**Issue by floto-trazalog** [Trazalog/yudi-tools-almproc#161]
Ambiente Producción - v2.2.18.1

Descripción

En la pantalla de Pedidos de trabajo, al dar clic en el botón "Agregar" el sistema no recupera el formulario completo para cargar el pedido de trabajo y guardar dicho registro, 

se deja un audio a modo de evidencia: https://drive.google.com/file/d/1myMo0AdDFgFmRANtsV9J0Dri8MLpHrWZ/view?usp=drive_link

![image](https://github.com/Trazalog/yudi-tools-almproc/assets/88331456/9dc58273-67b6-4c82-b71e-08bca2c296f7)

**Comment by jfernandez-trazalog** [comment]
Pablo M.

**Comment by floto-trazalog** [comment]
Solucionado, ídem versión
