### ISSUE TITLE
Tareas-->Pedidos Trabajo-->Agregar: que recupere el "Pedido Tango"

### ISSUE THREAD

**Issue by floto-trazalog** [Trazalog/yudi-tools-almproc#162]
Ambiente Test - v2.2.14

**Descripción:**
### 1)
Al guardar un nuevo Pedido de trabajo asociado a un "Pedido Tango", luego, presionar el botón _Imprimir_ el sistema recupera todos los campos menos el Nro. Pedido Tango. Lo correspondiente, sería que que se recupere en la primer instancia de impresión

https://github.com/Trazalog/traz-comp-tareasestandar/assets/88331456/568c46cb-eb20-48b2-a34a-50d5bc26cb6c

### 2)
También, sucede al escanear el cód. QR, no figura el Nro del Pedido Tango. Se puede observar en la imagen

![image](https://github.com/Trazalog/traz-comp-tareasestandar/assets/88331456/cf7aaa2d-fb85-451e-9cbd-aa7ede856c35)

**Pasos a seguir:**
1. En Tareas
2. Pedidos Trabajo yudica
3. Botón "Agregar" 
4. Completar los campos obligatorios del form
5. Clic en botón "Guardar"
6. Clic en botón "Imprimir" -observar el dato faltante "Pedido Tango"-
7. _Punto 2)_ Escanear el código QR -directamente, no figura-

**Comment by jfernandez-trazalog** [comment]
Pablo Marrelli.

**Comment by floto-trazalog** [comment]
Solucionado en ambiente de Test y ambiente Producción - v2.2.20
