### ISSUE TITLE
SOPORTE-->Tareas-->Pedidos trabajo: error al filtrar por "pedidos terminados" 

### ISSUE THREAD

**Issue by floto-trazalog** [Trazalog/yudi-tools-almproc#163]
Ambiente Producción - v2.2.20

**Descripción:**
En Pedidos de trabajo, cuando se filtra con el botón "Mostrar pedidos terminados" sale el siguiente cartel

![image](https://github.com/Trazalog/yudi-tools-almproc/assets/88331456/d6d96539-92b7-4c30-8371-513850ce91b5)

Y al dar clic en el botón "aceptar" la página se queda cargando por más de 15 minutos  
Luego, al revisar en la Consola del desarrollador y en Network, se obtiene lo siguiente:

![image](https://github.com/Trazalog/yudi-tools-almproc/assets/88331456/89b09251-f5d5-48c8-8db1-c66539ed7493)

**Pasos a reproducir:**
1. Ingresar en la URL: https://www.cloudtrazalog.com/traz-comp-dnato/main/login
2. Ingresar empresa: Yudica; | user: alejandroyudica@gmail.com  | pass:12345
3. Clic en el menú "Tareas"
4. Clic en "Pedidos trabajo"
5. Clic en el botón "Mostrar pedidos terminados"

**Comment by jfernandez-trazalog** [comment]
Pablo Marrelli.

**Comment by floto-trazalog** [comment]
Solucionado en v2.2.20
