### ISSUE TITLE
SOPORTE-->Etiquetas: Al imprimir no refresca los datos

### ISSUE THREAD

**Issue by floto-trazalog** [Trazalog/yudi-tools-almproc#165]
Ambiente Producción - v2.3.7

**Descripción:**
Al completar los campos obligatorios del nuevo pedido de trabajo e, imprimir la etiqueta inicial, desde el botón "Imprimir"  

![image](https://github.com/Trazalog/yudi-tools-almproc/assets/88331456/50ecb193-f6b4-45b4-ae71-c869211d25d6)

y luego, cargar otro nuevo pedido de trabajo, el sistema repite los datos del pedido ingresado anteriormente
Se agregan las imagenes de lo reportado por parte del cliente
Los números de pedidos de trabajo son los siguientes: 
* 36621
* 36622
* 36623

**Información adicional**
**Nota:**
Se ha probado en el ambiente de test, pero no se pudo reproducir el error. Existe un bug reportado que puede estar relacionado
issue #136 

**Impacto:**
Esto vuelve ineficiente la fluidez de las tareas del cliente, puesto que a la hora de imprimir el sistema recupera datos erróneos, essto fuerza al cliente a reiniciar el sistema o el logueo generando frustración al usar el soft.

**Resultado esperado:**
Que al imprimir la etiqueta inicial desde el botón "Imprimir" el sistema recupere los datos correctamente

**Comment by jfernandez-trazalog** [comment]
Gera Ramos.

**Comment by floto-trazalog** [comment]
Solucionado en v2.3.9.1
