### ISSUE TITLE
Tareas-->Pedidos trabajo: cerrar pedidos viejos

### ISSUE THREAD

**Issue by floto-trazalog** [Trazalog/yudi-tools-almproc#166]
Ambiente Producción - v2.3.9.1

**Descripción:** el cliente solicita cerrar todos los pedidos abiertos del año 2022 hasta el 30 de noviembre del 2023, cuando no estaba implementado Trazalog junto a Tango.

> **Detalles adicionales.**
Se recomienda borrar todos los pedidos de trabajo que se encuentran dentro de la fecha indicada arriba, tanto los que se encuentran con estado_En curso, Rechazo o Entregado_

**Comment by jfernandez-trazalog** [comment]
Pablo Marrelli.

**Comment by floto-trazalog** [comment]
Solucionado
