### ISSUE TITLE
SOPORTE-->Tareas-->Pedidos trabajo-->Etiqueta final: se rompe el formato de la etiqueta final al imprimir & Editar link

### ISSUE THREAD

**Issue by floto-trazalog** [Trazalog/yudi-tools-almproc#168]
Ambiente Test - v2.3.9.2

**Descripción:**
### 1) se rompe el formato:
Se sospecha que al agregar el nombre de un cliente extenso se rompe el formato de la etiqueta final al imprimirla y la impresión se realiza en 2 etiquetas en vez de 1. 

### 2) modificar el link de la etiqueta final (tanto en el Pintado y acabado final como desde el listado de registro de Pedidos)
cambiar el link www.yudicaneumaticos.com por

**Comment by jfernandez-trazalog** [comment]
Pablo Marrelli.-

**Comment by floto-trazalog** [comment]
### Desestimar el apartado 1)

**Comment by floto-trazalog** [comment]
Solucionado en v2.3.11
