### ISSUE TITLE
Tareas--> Pedido de Trabajo: Imprimir sin funcionalidad

### ISSUE THREAD

**Issue by aalfaro-trazalog** [Trazalog/yudi-tools-almproc#17]
**Descripción**: En el listado de pedidos de trabajo, si se selecciona la acción de imprimir no tiene funcionalidad alguna.

**Pasos para reproducir:** 

1. Seleccionar "Tareas"
2. Click en "Pedidos Trabajo"
3. En acciones, click en "Imprimir Comprobante"

https://user-images.githubusercontent.com/87376576/127665322-e69d7a13-8dd9-4156-9271-4a2d3ffc76cc.mp4

**Comment by lbgarcia** [comment]
@aalfaro-trazalog Aun no esta liberado este cambio. Actualmente esta en desarrollo
