### ISSUE TITLE
Mis Tareas-->Pintado y acabado final: correcciones de buttons, texto y alineación de check list

### ISSUE THREAD

**Issue by aalfaro-trazalog** [Trazalog/yudi-tools-almproc#19]
**Descripción:** 

- Si el usuario apreta por accidente primero el radio button "Aprobar" y luego el "rechazar", la pantalla muestra ambas opciones seleccionadas, cuando solo debería mostrar como seleccionada la última acción realizada (en este caso rechazar).

![image](https://user-images.githubusercontent.com/87376576/132250671-1e71c342-0ced-44de-b42d-330bdd045b58.png)

- El texto que aparece arriba de los check list, está diferente al de la maqueta

![image](https://user-images.githubusercontent.com/87376576/132250400-20c92b4f-df1a-42b3-a6f6-59a6c4d145cb.png)

debería quedar así 
![image](https://user-images.githubusercontent.com/87376576/132250474-9582bd4d-b078-4a73-8e5c-0fcd3cf32388.png)

**Propuesta de Mejora**
La altura del check debería quedar alineado con el nombre

https://user-images.githubusercontent.com/87376576/127699377-1cef34a3-f9f5-423d-8bd9-262a7c8b623b.mp4

**Pasos para reproducir:**

1. Seleccionar "Mis Tareas"
2. Click en un proceso de Pintado y acabado final
3. Acciones
4. Seleccionar opción de prueba de trabajo

**Comment by floto-trazalog** [comment]
Es claramente un bug el tema de los radio buttons, solo debe poder elegir si aprueba o no
En el caso del formulario, esta confuso el mensaje. El primer renglon habría que eliminarlo. En el segundo deberia decir "Seleccione con un - [v] los defectos encontrados", y las opciones respetar lo que dice el documento de analisis sin la palabra "ok".
