### ISSUE TITLE
Errores varios y ortograficos

### ISSUE THREAD

**Issue by Nahuel1705** [Trazalog/yudi-tools-almproc#2]
# En el formulario "Nuevo pedido de trabajo"
![image](https://user-images.githubusercontent.com/56811317/122081932-eba32d80-cdd5-11eb-98f4-f67b383945f7.png)
No hay razón para que el titulo del formulario este capitalizado, debería decir "Nuevo pedido de trabajo."

![image](https://user-images.githubusercontent.com/56811317/122082027-04134800-cdd6-11eb-8045-923191ebc70a.png)
El placeholder del input Código de proyecto debería decir "Código" con tilde y mayúscula inicial. Además algunos campos tienen placeholder y otros no, deberían estar en todos los inputs o en ninguno.

![image](https://user-images.githubusercontent.com/56811317/122082749-a29fa900-cdd6-11eb-95ae-8c07aeeceea1.png)
Debajo del input Código de proyecto hay un span que informa lo que debería entrar en el input, este span no ese ve en ningún otro lado así que se debería poner en todos los inputs o bien removerlo.

![image](https://user-images.githubusercontent.com/56811317/122083003-de3a7300-cdd6-11eb-9739-a126136afae8.png)
No hay razón para capitalizar Entrega, debería decir "Dirección de entrega:"

![image](https://user-images.githubusercontent.com/56811317/122083127-f8745100-cdd6-11eb-8ff5-d564703c4f02.png)
No hay razón para capitalizar Trabajo, debería decir "Fecha de trabajo:"

# En el formulario dinámico de "Nuevo pedido de trabajo"
![image](https://user-images.githubusercontent.com/56811317/122083772-894b2c80-cdd7-11eb-8ef0-d52d25d76093.png)
La palabra esta abreviada la palabra numero en el input de numero de serie mientras que en el numero de cubiertas esta completa. Si no hay problemas de espacio, ambas palabras deberían escribirse completas, sino, ambas deberían estar abreviadas

![image](https://user-images.githubusercontent.com/56811317/122084108-e34bf200-cdd7-11eb-84db-c89f0fa9e1ba.png)
Si se van a utilizar placeholders en los inputs estos deberían ser mas descriptivos, informando exactamente que se espera que se ingrese en el input.

**Comment by aalfaro-trazalog** [comment]
@lbgarcia lo único que no está arreglado es el primer apartado:
-No hay razón para que el titulo del formulario este capitalizado, debería decir "Nuevo pedido de trabajo."

**Comment by lbgarcia** [comment]
@aalfaro-trazalog Debido a que en todo Tools se trabaja con iniciales de titulos en mayúsculas se decidió no modificarlo como se solicitaba en este Issue
