### ISSUE TITLE
Tareas -> Pedidos de trabajo: No se guarda el pedido de trabajo

### ISSUE THREAD

**Issue by Nahuel1705** [Trazalog/yudi-tools-almproc#3]
Descripción: Luego de rellenar todo el formulario con datos del pedido, al presionar el botón guardar aparece un mensaje informando que hubo un error.

Pasos para reproducir:

1. Entrar a pedidos de trabajo
2. Click en botón "Agregar" para agregar un nuevo pedido.
3. Rellenar el formulario con los datos
4. Click en el botón "Guardar"

Datos que se intentaron utilizar en la prueba:
![image](https://user-images.githubusercontent.com/56811317/123681569-5dd93080-d820-11eb-8b54-5c0a39b226ce.png)

Mensaje de error recibido:
![image](https://user-images.githubusercontent.com/56811317/123681602-6598d500-d820-11eb-800a-f984cd001626.png)

**Comment by aalfaro-trazalog** [comment]
@lbgarcia solucionado!
