### ISSUE TITLE
Tareas -> Pedidos de trabajo: Se muestra de manera incorrecta el estado en el datatable

### ISSUE THREAD

**Issue by Nahuel1705** [Trazalog/yudi-tools-almproc#4]
Descripción: El estado se muestra de manera incorrecta en el datatable, al parecer se trae el nombre de la base de datos

![image](https://user-images.githubusercontent.com/56811317/123682821-e4dad880-d821-11eb-88d7-95e5f006b1dc.png)

**Comment by aalfaro-trazalog** [comment]
@lbgarcia  Actualizado en issue #16
