### ISSUE TITLE
Tareas -> Pedidos de trabajo: Al usar el boton "Ver Pedido" se rompe la vista y deja el sistema inoperable

### ISSUE THREAD

**Issue by Nahuel1705** [Trazalog/yudi-tools-almproc#5]
Descripción: Al presionar el botón "Ver Pedido" en el data table y, acto seguido, presionar en el botón "cerrar" salta a la pantalla "Mis Tareas" y queda todo opaco y sin poder hacer nada

Pasos para reproducir:
1. Abrir la pantalla de "Pedidos de trabajo"
2. Click en el botón "Ver Pedido" en algún pedido del data table.
3. Click en el botón "Cerrar" de la ventana modal emergente

![chrome-capture](https://user-images.githubusercontent.com/56811317/123857930-4f127c80-d8f9-11eb-8f61-db7beec46d45.gif)

**Comment by aalfaro-trazalog** [comment]
@lbgarcia en este primer video que te voy a mostrar, el bug que muestra Nahuel no aparece, pero si sería bueno mejorar los tiempos de carga, porque demora mucho y algún usuario puede pensar que se tildo.

https://user-images.githubusercontent.com/87376576/127558273-68fc9a77-ebf8-474e-b82a-598ff039acc2.mp4

Mientras que en esta otra secuencia de clicks, si se congela la pantalla, quedándose inoperable a menos que se recargue la página.


https://user-images.githubusercontent.com/87376576/127559148-3f45ec42-3f6e-492b-9997-19da989ceb7a.mp4
