### ISSUE TITLE
Mis Tareas--> Pintado y Acabado final: La Impresión de la Etiqueta no autocompleta datos

### ISSUE THREAD

**Issue by aalfaro-trazalog** [Trazalog/yudi-tools-almproc#52]
v.1.5.22
**Descripción:**
Al generar la impresión, la misma se encuentra con estilo correcto, pero no trae los datos ingresados en el sistema de "Zona" y "Cantidad".

![image](https://user-images.githubusercontent.com/87376576/138357864-0e41166f-ab93-442a-9560-38d28fb05381.png)

**Pasos para reproducir:**

1. En menú seleccionar "Mis Tareas"
2. Seleccionar un proceso de Pintado y Acabado final
3. Aprobar pedido
4. Click en "Impresión"

**Comment by floto-trazalog** [comment]
Al realizar la prueba se muestra en la etiqueta la "Cantidad", mas falta el dato de "Zona"

![Etiqueta](https://user-images.githubusercontent.com/88331456/142010424-7973351b-9d02-4990-a47b-a306196e9ae5.png)
