### ISSUE TITLE
Mis Tareas: Se pueden agregar comentarios vacíos

### ISSUE THREAD

**Issue by Nahuel1705** [Trazalog/yudi-tools-almproc#6]
Descripción: Se pueden atar comentarios vacos a un pedido de trabajo. No se esta validando esa entrada

Pasos para la reproducción:
1. Abrir pantalla "Mis Tareas"
2. Elegir una tarea de la lista
3. En la pestaña "Comentarios" ubicar el cursor en el campo para ingresar un nuevo comentario
4. Sin agregar nada en la entrada, hacer click en el boton "Agregar"

![chrome-capture](https://user-images.githubusercontent.com/56811317/123858934-73228d80-d8fa-11eb-89a3-9fe494364936.gif)

**Comment by aalfaro-trazalog** [comment]
@lbgarcia  sigue igual.
