### ISSUE TITLE
Tareas --> Pedido de Trabajo: Fecha-hora de fin, no coincide

### ISSUE THREAD

**Issue by aalfaro-trazalog** [Trazalog/yudi-tools-almproc#68]
v 2.0.3

Descripción:
Si revisamos el detalle de un pedido de trabajo finalizado, la fecha/hora de inicio coincide, pero la de finalizado no.
Aparentemente el servidor está 3hs adelantado.

![image](https://user-images.githubusercontent.com/87376576/158414783-3b796fb1-07e7-4fc7-b223-d7993f1b9085.png)

Pasos para reproducir:
1. En menú tarea, seleccionar Pedido de Trabajo
2. Elegir un pedido y dar click en ver detalles

**Comment by floto-trazalog** [comment]
Solucionado en v2.1.7.6
