### ISSUE TITLE
Tareas-->Pedidos de trabajo: en botón "Imprimir" no muestra Nro. de Orden (Vital)

### ISSUE THREAD

**Issue by floto-trazalog** [Trazalog/yudi-tools-almproc#70]
Ambiente test - v2.0.3

**Descripción:**
Al solicitar la impresión de la Etiqueta en algún Pedido de Trabajo, el sistema no muestra el Número de Orden, el cual debería figurar en la etiqueta

![RE-BUG](https://user-images.githubusercontent.com/88331456/158454168-88597c8a-530c-4442-9a58-74d55fe523d6.png)

**Pasos a reproducir:**

1. En menú Tareas
2. Dar click en Pedidos Trabajo
3. Dar click en el botón "Imprimir"

**Comment by aalfaro-trazalog** [comment]
Solucionado en v 2.0.7.1
