### ISSUE TITLE
Implementación-->Mis Tareas-->Agregar Nro. de Orden a la Bandeja de Tareas

### ISSUE THREAD

**Issue by floto-trazalog** [Trazalog/yudi-tools-almproc#71]
Ambiente Test - v2.0.4

**Descripción:**
Al agregar un Pedido de trabajo y guardarlo se pide que en la Bandeja de Tareas figure el Nro de Orden del pedido

![BUG-Soli-15](https://user-images.githubusercontent.com/88331456/158878313-2f871ffb-c63b-48cd-b3be-4b52609f2e16.png)

**Pasos a reproducir:**

1. Dar click en la Bandeja de Tareas

**Comment by aalfaro-trazalog** [comment]
Solucionado en v 2.0.8
