### ISSUE TITLE
Implementación-->Tareas-->Pedido Trabajo: permite imprimir sin haber guardado el formulario

### ISSUE THREAD

**Issue by floto-trazalog** [Trazalog/yudi-tools-almproc#72]
Ambiente Test - v2.0.4

**Descripción:**
Al cargar los datos del Pedido de trabajo el sistema permite imprimir sin haber guardado el formulario. Se recomienda eliminar el botón eliminar para no generar confusión al usuario 

![BUG-Soli-16](https://user-images.githubusercontent.com/88331456/158878602-e362c0cf-fd2d-4fa8-82b5-6c41a265a0dc.png)

**Pasos a reproducir:**

1. En el menú Tareas
2. Dar click en la pestaña Pedido de Trabajo
3. Dar click en el botón "Agregar"
4. Completar los datos obligatorios

**Comment by aalfaro-trazalog** [comment]
Solucionado en v 2.0.8
