### ISSUE TITLE
Implementación-->Pedido de Trabajo-->Agregar: modificar el input del campo "Código Pedido"

### ISSUE THREAD

**Issue by floto-trazalog** [Trazalog/yudi-tools-almproc#73]
Ambiente Test - v2.0.4

**Descripción:**
En el formulario del Pedido de Trabajo se recomienda cambiar el input a "Código de Pedido" para que sea intuitivo a la vista del usuario

![BUG-Soli-17](https://user-images.githubusercontent.com/88331456/158880885-8bb6c407-f57c-4d89-b4d9-b721f70311f9.png)

**Pasos a reproducir:**

1. En el menú Tareas
2. Dar click en la pestaña Pedido Trabajo
3. Dar click en el botón "Agregar"
4. Posicionarse en el primer campo "Código Pedido"

**Comment by aalfaro-trazalog** [comment]
Solucionado en v 2.0.7.1
