### ISSUE TITLE
Implementación-->Tareas -->Pedido Trabajo: agregar en la etiqueta el Código de Pedido

### ISSUE THREAD

**Issue by floto-trazalog** [Trazalog/yudi-tools-almproc#76]
Ambiente Test - v2.0.4

**Descripción:**
Al agregar un pedido de trabajo el sistema debería mostrar en la Etiqueta a Imprimir el "Código de Pedido" 

![BUG-18](https://user-images.githubusercontent.com/88331456/158883210-76c0300f-e51b-4631-b989-cd274ace80b8.png)

**Pasos a reproducir:**

1. En el menú Tareas
2. Dar click en la pestaña Pedido de Trabajo
3. Dar click en el botón de acción "Imprimir Comprobante"

**Comment by aalfaro-trazalog** [comment]
Se determino que no es necesario agregar el código de la etiqueta.
