### ISSUE TITLE
Implementación-->Pedidos Trabajo: cambiar colores de los diferentes estados de los pedidos

### ISSUE THREAD

**Issue by floto-trazalog** [Trazalog/yudi-tools-almproc#77]
Ambiente Test - v2.0.4

**Descripción:**
Se recomienda cambiar los colores de los diferentes estados en la tabla de Pedidos de Trabajo

- En curso --> Azul
- Rechazado --> Rojo
- Entregado --> Verde

![BUG-19](https://user-images.githubusercontent.com/88331456/158889181-8bafbce7-ffcd-4168-8064-2799b39d2256.png)

**Pasos a reproducir:**

1. En el menú Tareas
2. Dar click en la pestaña "Pedido Trabajo"
3. Ver tabla

**Comment by aalfaro-trazalog** [comment]
Solucionado en v 2.0.8
